import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//@ts-ignore
import "./globals.css";
import { MuiThemeProvider } from "@/context/MuiThemeContext";
import { AuthProvider } from "@/context/AuthContext";
import StoreProvider from "@/lib/store/StoreProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <MuiThemeProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </MuiThemeProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
