import { Salon, PricingPackage } from './types';

export const MOCK_SALONS: Salon[] = [
  {
    id: '1',
    name: 'Salon Parami',
    category: 'Gampaha',
    location: 'Minuwangoda',
    district: 'Minuwangoda, Gampaha',
    image: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
    rating: 4.8,
    reviews: 42,
    description: 'Step into salon Parami, an oasis of chic, sophistication rendered in contemporary elegance with a tranquil ambiance that whispers style and class. Salon Parami offers exceptional services and a warm atmosphere tailored to embrace your intensity.',
    services: [
      { id: '1', name: 'Hair Cutting', products: ['Larael', 'Belois', 'Keune', 'Dreamcrm'] ,category: 'Hair'},
      { id: '2', name: 'Hair Coloring', products: ['Larael', 'Belois', 'Keune', 'Dreamcrm'] ,category: 'Hair'},
      { id: '3', name: 'Bridal Dressing', products: ['Larael', 'Derma', 'Kryples'] ,category: 'Bridal'},
      { id: '4', name: 'Normal Dressing', products: ['Larael', 'Derma', 'Kryples'] ,category: 'Body'},
      { id: '5', name: 'Hair straightening', products: ['Larael', 'Belois', 'Keune', 'Dreamcrm', 'Glant'] ,category: 'Hair'},
      { id: '6', name: 'Hair Rebonding', category: 'Hair' },
      { id: '7', name: '24K luxury gold facial treatment', category: 'Facial' },
      { id: '8', name: 'Whiting facial treatment', category: 'Facial' },
      { id: '9', name: 'Normal facial treatment', category: 'Facial' },
      { id: '10', name: 'pigmentation removal facial treatment', category: 'Facial' },
      { id: '11', name: 'Ultrasonic Facial Treatment', category: 'Facial' },
      { id: '12', name: 'Low high frequency facial', category: 'Facial' },
      { id: '13', name: 'Hydrafacial Facial Treatment', category: 'Facial' },
      { id: '14', name: 'Special acne and Pimple treatment', category: 'Facial' },
      { id: '15', name: 'High Frequency Galvanic (Electrotherapy) Facial', category: 'Facial' },
      { id: '16', name: 'Ultrasound Facial', category: 'Facial' },
      { id: '17', name: 'Serum facial (Anti-aging Anti wrinkle Facial)', category: 'Facial' },
      { id: '18', name: 'Nail Polish', category: 'Nails' },
      { id: '19', name: 'Gel Nail Polish', category: 'Nails' },
      { id: '20', name: 'Nail Extender', category: 'Nails' },
      { id: '21', name: 'Body Wax', category: 'Body' },
      { id: '22', name: 'Body Polish', category: 'Body' },
      { id: '23', name: 'Body Bleach', category: 'Body' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Minuwangoda, Gampaha',
    },
    qualifications: ['NVQ 4 Certificate (Hair, Beauty, Bridal)'],
    experience: ['15 Years Experience in Salon Field', '05 Years Experience in Beauty Device Operating'],
    socialMedia: {
      tiktok: 'salonparami',
    },
  },
  {
    id: '2',
    name: 'Salon Dammi',
    category: 'CSI',
    location: 'Udugampola',
    district: 'Udugampola, Gampaha',
    image: 'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    rating: 4.6,
    reviews: 38,
    description: 'Professional salon offering comprehensive beauty and hair services.',
    services: [
      { id: '1', name: 'Hair Cutting', category: 'Hair' },
      { id: '2', name: 'Hair Coloring', category: 'Hair' },
      { id: '3', name: 'Bridal Dressing', category: 'Bridal' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Udugampola, Gampaha',
    },
    qualifications: ['Professional Certifications'],
    experience: ['10+ Years Experience'],
  },
  {
    id: '3',
    name: 'Salon Chamari And Academy',
    category: 'ACADEMY & SALON',
    location: 'Minuwangoda',
    district: 'Minuwangoda, Gampaha',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    rating: 4.7,
    reviews: 45,
    description: 'Academy and professional salon providing training and services.',
    services: [
      { id: '1', name: 'Hair Services', category: 'Hair' },
      { id: '2', name: 'Facial Treatments', category: 'Facial' },
      { id: '3', name: 'Bridal Services', category: 'Bridal' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Minuwangoda, Gampaha',
    },
    qualifications: ['Academy Certified'],
    experience: ['Comprehensive Training Programs'],
  },
  {
    id: '4',
    name: 'Salon Opara',
    category: 'ACADEMY & SALON',
    location: 'Ganemulla',
    district: 'Ganemulla, Gampaha',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
    rating: 4.5,
    reviews: 35,
    description: 'Premium salon and academy offering top-tier beauty services.',
    services: [
      { id: '1', name: 'Hair Care', category: 'Hair' },
      { id: '2', name: 'Skin Care', category: 'Facial' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Ganemulla, Gampaha',
    },
    qualifications: ['Professional Staff'],
    experience: ['8+ Years in Industry'],
  },
  {
    id: '5',
    name: 'Salon Sujee',
    category: 'Gampaha',
    location: 'Kotugoda',
    district: 'Kotugoda, Gampaha',
    image: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
    rating: 4.4,
    reviews: 30,
    description: 'Modern salon with experienced staff and comprehensive services.',
    services: [
      { id: '1', name: 'Hair Services', category: 'Hair' },
      { id: '2', name: 'Beauty Treatments', category: 'Beauty' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Kotugoda, Gampaha',
    },
    qualifications: ['Certified Professionals'],
    experience: ['7+ Years Experience'],
  },
  {
    id: '6',
    name: 'Nadee Salon & Saree Center',
    category: 'Gampaha',
    location: 'Ganemulla',
    district: 'Ganemulla, Gampaha',
    image: 'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    rating: 4.6,
    reviews: 40,
    description: 'Combined salon and saree center offering beauty and fashion services.',
    services: [
      { id: '1', name: 'Hair Services', category: 'Hair' },
      { id: '2', name: 'Bridal Dressing', category: 'Bridal' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Ganemulla, Gampaha',
    },
    qualifications: ['Professional Staff'],
    experience: ['10+ Years in Business'],
  },
  {
    id: '7',
    name: 'Salon Robin\'s',
    category: 'Gampaha',
    location: 'Kandana',
    district: 'Kandana, Gampaha',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    rating: 4.5,
    reviews: 33,
    description: 'Professional salon with dedicated staff and quality services.',
    services: [
      { id: '1', name: 'Hair Services', category: 'Hair' },
      { id: '2', name: 'Styling', category: 'Style' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Kandana, Gampaha',
    },
    qualifications: ['Certified Stylists'],
    experience: ['6+ Years Experience'],
  },
  {
    id: '8',
    name: 'Salon Ewon',
    category: 'Gampaha',
    location: 'Asgriya',
    district: 'Asgriya, Gampaha',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
    rating: 4.7,
    reviews: 44,
    description: 'Upscale salon with modern facilities and expert beauticians.',
    services: [
      { id: '1', name: 'Complete Hair Care', category: 'Hair' },
      { id: '2', name: 'Spa Services', category: 'Spa' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Asgriya, Gampaha',
    },
    qualifications: ['Expert Staff'],
    experience: ['12+ Years in Industry'],
  },
  {
    id: '9',
    name: 'Salon Udi',
    category: 'CSI',
    location: 'Munnakkara',
    district: 'Munnakkara, Negombo',
    image: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
    rating: 4.3,
    reviews: 28,
    description: 'Quality salon providing professional beauty services.',
    services: [
      { id: '1', name: 'Hair Services', category: 'Hair' },
      { id: '2', name: 'Beauty Treatments', category: 'Beauty' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Munnakkara, Negombo',
    },
    qualifications: ['Professional Team'],
    experience: ['5+ Years Experience'],
  },
  {
    id: '10',
    name: 'Salon Shaivy and Academy',
    category: 'ACADEMY & SALON',
    location: 'Ragama',
    district: 'Ragama',
    image: 'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    rating: 4.8,
    reviews: 50,
    description: 'Premier salon and training academy with comprehensive services.',
    services: [
      { id: '1', name: 'Professional Hair Care', category: 'Hair' },
      { id: '2', name: 'Advanced Beauty Treatments', category: 'Beauty' },
      { id: '3', name: 'Training Programs', category: 'Training' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1560066620-3a8b3c4dfe4f?w=400&h=300&fit=crop',
    ],
    contact: {
      phone: '+94 75 833 8180',
      whatsapp: '+94 75 833 8180',
      address: 'Ragama',
    },
    qualifications: ['Academy Certified', 'Expert Trainers'],
    experience: ['15+ Years in Training and Services'],
  },
];

export const MOCK_PRICING_PACKAGES: PricingPackage[] = [
  {
    id: '1',
    duration: '06 MONTHS PACKAGE',
    price: 65,
    pricePerDay: 65,
    billed: 'Billed for 180 days (06 Months)',
    benefits: [
      'Having the opportunity to enter among the best salons in the island',
      'You can upload up to 30 Service photos',
      'You can upload up to 6 Service videos',
      'You can change Up to 10 Photos withing month',
      'You can change Up to 4 Videos withing month',
      'You can add Your photo, Qualification, Services, Programs',
      'You can add website, social media, contact details on same place',
      '24 Contact Support',
    ],
    extraBenefits: [
      { label: 'RS 1000 Free Voucher', amount: 'RS.1000' },
    ],
  },
  {
    id: '2',
    duration: '12 MONTHS PACKAGE',
    price: 55,
    pricePerDay: 55,
    billed: 'Billed for 365 days (12 Months)',
    benefits: [
      'Having the opportunity to enter among the best salons in the island',
      'You can upload up to 45 Service photos',
      'You can upload up to 10 Service videos',
      'You can change Up to 15 Photos withing month',
      'You can change Up to 10 Videos withing month',
      'You can add Your photo, Qualification, Services, Programs',
      'You can add website, social media, contact details on same place',
      '24 Contact Support',
    ],
    extraBenefits: [
      { label: 'RS 1500 Free Voucher', amount: 'RS.1500' },
    ],
    isPopular: true,
  },
];
